### ISSUE TITLE
Timeout on large files

### ISSUE THREAD

**Issue by vic-t** [kennell/curldrop#3]
I just tried to transfer a large file using curldrop. After exactly 30 seconds, the upload is interrupted, the server complains about a [CRITICAL] WORKER TIMEOUT.

**Comment by kennell** [comment]
This is most likely caused by a gunicorn limitation, see http://docs.gunicorn.org/en/19.3/settings.html 

Perhaps i can add a passthrough flag for the next release.

**Comment by kennell** [comment]
Added a `--timeout` option in the latest release (version 1.0.3)
