### ISSUE TITLE
BaseURL should work with missing trailing slash

### ISSUE THREAD

**Issue by paulcmal** [kennell/curldrop#4]
Hi, and thank you for maintaining curldrop. I just found out about it and it's a real pleasure to use <3

An issue i stumbled upon when setting it up is that the `/` between the baseURL and the file uuid was missing in the generated URLs, because i forgot to put a trailing slash in my baseURL.

Although in the example provided in the README there is a trailing slash, i feel like it's a silly issue that could be addressed with a single line patch so i figured i'd open an issue here to let you know about it :)

**Comment by kennell** [comment]
Hi, thank you for the suggestion. It's not worth adding a extra line in my mind, error should be obvious to the user ;)

**Comment by paulcmal** [comment]
Hi, i agree it will be obvious to a sysadmin deploying the service. However i believe if we can take a few extra steps (without compromising security or adding too much bloat) to make people's lives easier and deployment pain-free then it's worth it.

That's my personal approach to computing and i would understand if you'd rather keep the KISS mindset for the curldrop project :)
